### ISSUE TITLE
Bass.Init default frequency

### ISSUE THREAD

**Issue by mysteryx93** [ManagedBass/ManagedBass#106]
ManagedBass.Bass.Init has the frequency parameter set to 44100 by default.

However, [according to BASS doc](http://www.bass.radio42.com/help/html/5bf1ebdd-a59c-60b5-4866-6c3ae26e2de5.htm)

> BASS_DEVICE_FREQ | Set the device's output rate to freq, otherwise leave it as it is.

The default value should be the device's configured sample rate. Currently there doesn't seem to be a way to use the device's frequency.

**Comment by peppy** [comment]
Check the same documentation page you linked (search for `The sample format specified in the freq and flags parameters has no effect on`). The setting you choose here shouldn't be used in most (every?) case these days. That's up the the host operating system to choose, unless you go lower level (ie. use WASAPI or otherwise).

**Comment by mysteryx93** [comment]
Ah! Good.

Btw I'm doing pitch-shifting from 440hz to 432hz and am looking to get the best possible quality. BASS already is giving better quality than NAudio+SoundTouch. Is there any way to further improve it?

[Code is here](https://github.com/mysteryx93/MediaPlayerUI.NET/blob/master/Avalonia.Bass/BassPlayerHost.cs#L339)

I just changed TempoUseAAFilter=0 and saw some quality improvement.
