### ISSUE TITLE
ManagedBass.Midi NuGet package does not expose MidiIn methods

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [ManagedBass/ManagedBass#54]
I need to use ManagedBass.Midi to read from MIDI input devices, but the ManagedBass.Midi package does not expose any methods inside the [MidiIn.cs](https://github.com/ManagedBass/ManagedBass/blob/master/src/AddOns/BassMidi/Shared/PInvoke/MidiIn.cs) file because it's hidden behind a compiler flag (`__IOS__ || __DESKTOP__`). Is there any reasoning behind this? Can a separate package be published for desktop/iOS platforms that does have this enabled?

**Comment by smoogipoo** [comment]
Any updates to this issue?

**Comment by smoogipoo** [comment]
Any updates to this one? We'd like to use ManagedBass.Midi in our project (see referencing PR).

**Comment by MathewSachin** [comment]
I'm really sorry I had missed this issue.

BASS does not support MIDI input on Android devices. The supported platforms for this feature are Desktops (Widows, Mac, Linux) and iOS. That's the reason for the `__IOS__ || __DESKTOP__` compiler flag. So, the NuGet package should contain MIDI input support for `.NET Framework` and `Xamarin.iOS` but not for `Xamarin.Android`.
Also, since the support is not cross-platform, this has been **excluded** from the `.NET Standard` version.

I'll try to confirm if installing the package to a `.NET Framework` project, exposes the MIDI input methods, and let you know shortly.

**Comment by MathewSachin** [comment]
I don't know how to apologise for my negligence.
I've got some time now, so I'm trying my best to tackle pending issues in my projects.

I've released v3 of ManagedBass recently.
There are not many changes except that most of the packages use the same DLLs on iOS as on other platforms.
Separate DLLs are still used for `Bass`, `BassMidi` and `BassEnc` packages.
Except these 3 packages, all other packages require the use of [dllmap](https://github.com/ManagedBass/ManagedBass/blob/master/src/app.config).

Please check if v3 solves this issue for you.

I'm afraid about making a single library for `BassMidi` and putting MidiIn support into it.
The reason is that I had heard somewhere that Play store certification fails if there are unresolved `[DllImport]`s. This can happen if MidiIn methods are not present in the android `.so` library of `BASSmidi`. If anyone can confirm that this is not true, then I can go forward and use a single library for all platforms.

**Comment by HoLLy-HaCKeR** [comment]
I checked the x86_64 .so file found [on the BASS forums](https://www.un4seen.com/forum/?topic=13225), and I couldn't find any exports matching `BASS_MIDI_In`. My main goal was to get MIDI input working on android so I'll probably have to go with another library then.
