### ISSUE TITLE
Bass.CreateStream(byte[]) with AAC stream causes FileFormat error on Linux

### ISSUE THREAD

**Issue by tommaier123** [ManagedBass/ManagedBass#94]
When creating a stream from a byte array on linux 0 is always returned and playback doesn't work.
On Windows everything works as expected.

**Comment by tommaier123** [comment]
Looking at the LastError it has a FileFormat error. it seems like decoding the AAC data is the problem. Is AAC not supported on Linux?

**Comment by DustinBond** [comment]
AAC is supported on Linux, you may have to go to the Bass website and download the plug in code then load that code for support. Not in my office right now, or I would attach some sample code.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Nova_Max ***@***.***>
Sent: Monday, June 21, 2021 4:49:05 AM
To: ManagedBass/ManagedBass ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [ManagedBass/ManagedBass] Bass.CreateStream(byte[]) with AAC stream causes FileFormat error on Linux (#94)


Looking at the LastError it has a FileFormat error. it seems like decoding the AAC data is the problem. Is AAC not supported on Linux?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FManagedBass%2FManagedBass%2Fissues%2F94%23issuecomment-864969680&data=04%7C01%7Cdustinb%40iheartmedia.com%7Ce65abb7533424b6c810c08d934aa9314%7C122a527e5b714eba878d9810b495b9e3%7C0%7C0%7C637598729514248072%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QgPMjyksBD4bj6PX4e8IzUCAcT2qsdWPkDcAIkTIYp0%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIW3H6YC5AIK4XFTG5IEYF3TT4RLDANCNFSM467PXXFA&data=04%7C01%7Cdustinb%40iheartmedia.com%7Ce65abb7533424b6c810c08d934aa9314%7C122a527e5b714eba878d9810b495b9e3%7C0%7C0%7C637598729514248072%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Fw2Pjgui327VEIDHEN4KxwBbORo4CMZdWiv2FjlgCkc%3D&reserved=0>.

CAUTION: This message originated from outside of the company. Please take all precautions when opening attachments or links from outside sources.

**Comment by tommaier123** [comment]
Thanks for the tip,

I have now downloaded the plugin. Apparently its necessary for Linux but not Windows and Osx.
This is what I am doing now.
```
Bass.Init();
string plugin = Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location), "libbass_aac.so");
if (RuntimeInformation.IsOSPlatform(OSPlatform.Linux)) Bass.PluginLoad(plugin);

var channel = Bass.CreateStream(array, 0, array.Length, BassFlags.Default);
Bass.ChannelPlay(channel);
```
Unfortunately the error still happens.
I was also a bit unsure which library file to use. Similarly to libbass itself there is on in the root folder and one in the x64 folder. For the lib I am using the x64 version which seems to work but the x64 version of the plugin causes the whole program to crash without any exception. So instead I am using the version from the root folder of the plugin download.
